import swaggerJsdoc from 'swagger-jsdoc';

const options = {
  // List of files to be processed.
  apis: [
    './src/main/api/**/*.js',
    './src/main/models/**/*.js',
    './src/main/api/**/*.ts',
    './src/main/models/**/*.ts',
  ],
  basePath: '/api/v1',
  swaggerDefinition: {
    info: {
      description: 'Test API with autogenerated swagger doc',
      swagger: '2.0',
      title: 'Todo API',
      version: '1.0.0',
    },
    securityDefinitions: {
      Bearer: {
        type: 'apiKey',
        name: 'Authorization',
        in: 'header',
      },
    },
  },
};
const specs = swaggerJsdoc(options);
export default specs;
